### ISSUE TITLE
Unable to use with cargo-leptos SSR

### ISSUE THREAD

**Issue by darrenpicard25** [eboody/styled#2]
Hi there attempting to get a leptos app up and running with server side rendering (ssr) and I want styling (without tailwind). Tried using crates like [stylers](https://github.com/abishekatp/stylers) but ran into issues of leptos build orders and such. I have now set my eyes on your little project in an attempt to hopefully get this working. However when i tried it out i was not able to get it to work. `cargo-leptos build` seems to work fine (funny enough) but `cargo leptos serve` and `cargo-leptos watch` both seem to fail with 
```
thread 'main' panicked at /home/darren/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5847:9:
cannot call wasm-bindgen imported functions on non-wasm targets
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/darren/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_axum-0.4.8/src/lib.rs:1042:14:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(9), ...)
```

Now this is probably a cargo-leptos thing and probably has nothing to do with your package, but I'm hoping maybe you might have some idea how to fix and get what i want working. 

And if you have no idea would greatly appreciate if you know of some examples of using component level styling with SSR that is not tailwind would also be appreciated.

I will most likely be reaching out to leptos team if you are unable to help

**Comment by eboody** [comment]
Hey there! you're right, I dont think this is particular to this crate, though I could be wrong. If you remove this crate from your Cargo.toml (and any references to it in your code) does everything compile as you'd expect it to?

**Comment by klautcomputing** [comment]
While I am not the OP I can confirm that just adding the two crates to my Cargo.toml breaks it. Happy to link some code if you want me to.

**Comment by klautcomputing** [comment]
Steps to reproduce:
1. Clone https://github.com/klautcomputing/hive-leptos
2. edit `Cargo.toml` and pull in `styled` and `stylist`
3. edit `app/Cargo.tml` do the same
4. `cargo leptos watch`
5. panic
```
thread 'main' panicked at /home/leex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5847:9:
cannot call wasm-bindgen imported functions on non-wasm targets
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/8550f15e148407159af401e02b1d9259762b3496/library/std/src/panicking.rs:649:12
   1: js_sys::global::get_global_object::Global::get_self::__wbg_self_1ff1d729e9aae938
             at /home/leex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.64/src/lib.rs:5847:
```

**Comment by ImTheSquid** [comment]
Will be fixed by #4
